//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergencyViewer.Data.Concrete.EF
{
    using System;
    using System.Collections.Generic;

    public partial class EmergencyEvent
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> OccuranceDate { get; set; }
        public Nullable<int> EventType { get; set; }
        public Nullable<int> InfoSourceId { get; set; }

        public virtual InfoSource InfoSource { get; set; }
    }
}
