//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using EmergencyViewer.Data.Entities;

namespace EmergencyViewer.Data.Concrete.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventsDb : DbContext
    {
        public EventsDb()
            : base("name=EventsDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmergencyEvent> EmergencyEvents { get; set; }
        public virtual DbSet<InfoSource> InfoSources { get; set; }
    }
}
